# Generated by Django 4.0.6 on 2022-08-26 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(blank=True, max_length=255)),
                ('acc_name', models.CharField(blank=True, max_length=255)),
                ('savings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25)),
                ('symbol', models.CharField(blank=True, max_length=25)),
                ('name', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(default=False, upload_to='')),
                ('signature', models.ImageField(default=False, upload_to='')),
                ('employment_status', models.BooleanField(default=False)),
                ('marital_status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('pin', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(blank=True, default=False, max_length=15)),
                ('transaction_code', models.CharField(blank=True, default=False, max_length=15)),
                ('charge', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default=False, max_length=15)),
                ('customer', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
                ('destination_account', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('origin_account', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_Receipt', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('transaction_cost', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('currency', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=False)),
                ('date_time', models.DateTimeField(null=True)),
                ('transaction', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction')),
                ('wallet', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(default=datetime.datetime.now)),
                ('total_amount', models.PositiveIntegerField()),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notification', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('borrow_date_and_time', models.DateTimeField(default='')),
                ('interest_rate', models.PositiveIntegerField()),
                ('payment_due_date', models.DateTimeField(blank=True, null=True)),
                ('loan_balance', models.PositiveIntegerField()),
                ('loan_term', models.TextField()),
                ('loan_status', models.CharField(default='Unpaid', max_length=15, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan', to='wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_loan', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=25)),
                ('card_name', models.CharField(blank=True, max_length=25)),
                ('pin_number', models.CharField(blank=True, max_length=5)),
                ('security_code', models.CharField(blank=True, max_length=5)),
                ('card_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
