# Generated by Django 4.0.6 on 2022-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.ImageField(upload_to=''),
        ),
    ]
