# Generated by Django 4.0.6 on 2022-09-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_customer_profile_alter_customer_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='signature',
        ),
    ]
