# Generated by Django 4.0.6 on 2022-10-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_customer_profile_remove_customer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='savings',
            field=models.IntegerField(default=0),
        ),
    ]
